apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      # targetRevision: "*"
      helm:
        releaseName: ingress-nginx
        valueFiles:
          - $values/06-continuous-delivery/system/nginx-ingress-controller-kind/values.yaml
    - repoURL: git@github.com:justingodden/mlops-made-easy-project-code.git
      # targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
