apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: my-app
  type: "{{ .Values.service.type }}"
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8501